//
//  UIColor+Laboratory.h
//  Laboratory-objc
//
//  Created by qeeniao35 on 2019/1/18.
//  Copyright © 2019 CodeZ. All rights reserved.
//

#import <UIKit/UIKit.h>

#ifndef LabColor

#define LabColor(args) [UIColor colorWithHexString:args]

#endif

@interface UIColor (Laboratory)
#pragma mark - Colors from Hex Strings

/**
 *  Creates and returns a @c UIColor object based on the specified hex string.
 *
 *  @param string The hex string.
 *
 *  @return A @c UIColor object in the RGB colorspace.
 *
 *
 *  @since 2.0
 */
+ (UIColor * _Nullable)colorWithHexString:(NSString* _Nonnull)string;

/**
 *  Creates and returns a @c UIColor object based on the specified hex string.
 *
 *  @param string The hex string.
 *  @param alpha  The opacity.
 *
 *  @return A @c UIColor object in the RGB colorspace.
 *
 *
 *  @since 2.0
 */
+ (UIColor * _Nullable)colorWithHexString:(NSString * _Nonnull)string withAlpha:(CGFloat)alpha;


#pragma mark - 随机颜色
/**
 在限制范围内随机颜色

 @param colors 随机颜色组
 @return 随机的颜色
 */
+ (UIColor * _Nullable)colorWithRandomColorInArray:(NSArray<UIColor *> *_Nullable)colors;


#pragma mark - 从图片中抓取颜色
/**
 *  Returns the average color generated by averaging the colors of a specified image.
 *
 *  @param image A specified @c UIImage.
 *
 *  @return A flat @c UIColor object in the HSB colorspace.
 *
 *  @since 2.0
 */
+ (UIColor *_Nullable)colorWithAverageColorFromImage:(UIImage *_Nonnull)image;

/**
 *  Returns the average color generated by averaging the colors of a specified image.
 *
 *  @param image A specified @c UIImage.
 *  @param alpha The opacity.
 *
 *  @return A flat @c UIColor object in the HSB colorspace.
 *
 *  @since 2.0
 */
+ (UIColor *_Nonnull)colorWithAverageColorFromImage:(UIImage *_Nonnull)image withAlpha:(CGFloat)alpha;

#pragma mark - 实例
/**
 颜色值
 
 @return 十六位制颜色编码字符串
 */
- (NSString *_Nullable)hexValue;

@end

