platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'Laboratory-objc' do

pod 'MBProgressHUD', '~> 1.1.0'

pod 'MJRefresh', '~> 3.1.15.7'

# 流式布局
#pod 'iCarousel'

#socket即时通讯
pod 'CocoaAsyncSocket'

end
